version: "3"

services:
    backend-api:
        build:
            context: .
        ports:
        - "8000:8000"
        volumes:
        - .:/backend-api
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        