version: "3"

services:
    backend-api:
        build:
            context: .
        ports:
        - "8000:8000"
        volumes:
        - .:/backend-api
        command: >
            sh -c  "python manage.py wait_for_db &&
                    python manage.py makemigrations &&
                    python manage.py migrate && 
                    python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DB_HOST=db
            - DB_NAME=backend-api
            - DB_USER=postgres
            - DB_PASS=menem2020
        depends_on:
            - db
    db:
        image: postgres:12.4
        environment:
            - POSTGRES_DB=backend-api
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=menem2020
            - POSTGRES_INITDB_ARGS="--data-checksums"
