# Generated by Django 3.1 on 2020-09-14 04:10

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tag', models.CharField(max_length=50)),
                ('subtag', models.CharField(max_length=50)),
                ('descrpicion', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.models.upload_image_path)),
                ('cont_mail', models.CharField(max_length=100)),
                ('cont_insta', models.CharField(max_length=100)),
                ('cont_whatsapp', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=100)),
                ('cobertura', models.CharField(max_length=120)),
                ('envio', models.CharField(max_length=80)),
                ('horarios', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empren', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
