# Generated by Django 3.1 on 2020-09-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emprendimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprendimiento',
            old_name='horarios',
            new_name='horario',
        ),
    ]
