# Generated by Django 3.1 on 2020-09-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200914_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprendimiento',
            old_name='descrpicion',
            new_name='descripicion',
        ),
    ]
