# Generated by Django 3.1 on 2020-09-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200914_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprendimiento',
            old_name='descripicion',
            new_name='descripcion',
        ),
    ]
