# Generated by Django 3.1 on 2020-09-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200914_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
