# Generated by Django 3.1 on 2020-09-14 22:12

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200914_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=core.models.upload_image_path)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=core.models.upload_image_path)),
                ('precio', models.IntegerField(default=0)),
                ('inmediato', models.BooleanField(default=False)),
                ('stock', models.BooleanField(default=True)),
                ('emprendimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='core.emprendimiento')),
            ],
        ),
    ]
