# Generated by Django 3.1 on 2020-09-14 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='name',
        ),
    ]
