# Generated by Django 3.1 on 2020-09-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200914_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='tag',
        ),
    ]
